import uuid
from django.db import models
from .socio import Socio
from .obraSocial import ObraSocial


class Datos_Medicos(models.Model):
    """Medical information of the member.

    This model registers health insurance data of an existing member of the
    gym.


    Attributes:
        id_medico(uuid): autogenerated primary key.
        osNumero_socio(int): health insurance number.
        os_plan(str): health insurance plan.
        contacto_urgencia(str): emergency contact person full name.
        contacto_parentesco(str): emergency contact person relationship.
        numero_urgencia(int): phone number of the emergency contact.
        socio(obj): the already registered membee whom the medical information
          is about, the field is linked to the socio model..
        obra_social(obj): health insurance company, linked to the obraSocial
          model, the company has to be registered in that model to finish
          the medical information registration.
    """

    id_medico = models.UUIDField(primary_key=True,
                                 default=uuid.uuid4,
                                 editable=False)
    osNumero_socio = models.BigIntegerField("numero de socio obra social",
                                            blank=True,
                                            null=True)
    os_plan = models.CharField("plan obra social",
                               max_length=20,
                               blank=True,
                               null=True)
    contacto_urgencia = models.CharField("contacto de urgencia",
                                         max_length=70,
                                         blank=True,
                                         null=True)
    contacto_parentesco = models.CharField("parentesco",
                                           max_length=20,
                                           blank=True,
                                           null=True)
    numero_urgencia = models.IntegerField("numero en caso de urgencia",
                                          blank=True,
                                          null=True)
    socio = models.OneToOneField(Socio, on_delete=models.CASCADE)
    obra_social = models.ForeignKey(ObraSocial,
                                    on_delete=models.CASCADE,
                                    blank=True,
                                    null=True)

    def __str__(self):
        return "{} {}".format(self.contacto_urgencia, self.numero_urgencia)

    class Meta:
        db_table = 'abmsocios_datos_medicos'
