# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_telefono', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(verbose_name='numero de telefono')),
                ('tipo', models.CharField(choices=[('PR', 'Personal'), ('LB', 'Laboral')], default='PR', max_length=2)),
            ],
        ),        
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('departamento', models.CharField(max_length=4)),
                ('barrio', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('PR', 'Personal'), ('LB', 'Laboral')], default='PR', max_length=2)),
            ],
        ),        
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_socio', models.IntegerField(verbose_name='numero de socio')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('correo', models.EmailField(max_length=150)),
                ('fecha_inscripcion', models.DateField(default=datetime.date.today, verbose_name='fecha de inscripcion')),
                ('apto_fisico', models.BooleanField(default=False)),
                ('fecha_apto', models.DateField(verbose_name='fecha de apto fisico')),
                ('estado', models.BooleanField(default=True)),
                ('domicilios', models.ManyToManyField(to='abmsocios.Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='DatosMedicos',
            fields=[
                ('id_medico', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('osNumero_socio', models.BigIntegerField(verbose_name='numero de socio obra social')),
                ('os_plan', models.CharField(max_length=20, verbose_name='plan obra social')),
                ('contacto_urgencia', models.CharField(max_length=70, verbose_name='contacto de urgencia')),
                ('contacto_parentesco', models.CharField(max_length=20, verbose_name='parentesco')),
                ('numero_urgencia', models.IntegerField(verbose_name='numero en caso de urgencia')),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='abmsocios.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id_obra', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=10)),
                ('numero_urgencia', models.IntegerField(verbose_name='numero de emergencia')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='telefonos',
            field=models.ManyToManyField(to='abmsocios.Telefono'),
        ),
    ]
