# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmedicos',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abmsocios.Socio'),
        ),
    ]
