# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0002_auto_20170515_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosmedicos',
            name='obra_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abmsocios.ObraSocial'),
        ),
        migrations.AlterField(
            model_name='datosmedicos',
            name='contacto_parentesco',
            field=models.CharField(max_length=20, null=True, verbose_name='parentesco'),
        ),
        migrations.AlterField(
            model_name='datosmedicos',
            name='contacto_urgencia',
            field=models.CharField(max_length=70, null=True, verbose_name='contacto de urgencia'),
        ),
        migrations.AlterField(
            model_name='datosmedicos',
            name='numero_urgencia',
            field=models.IntegerField(null=True, verbose_name='numero en caso de urgencia'),
        ),
        migrations.AlterField(
            model_name='datosmedicos',
            name='osNumero_socio',
            field=models.BigIntegerField(null=True, verbose_name='numero de socio obra social'),
        ),
        migrations.AlterField(
            model_name='datosmedicos',
            name='os_plan',
            field=models.CharField(max_length=20, null=True, verbose_name='plan obra social'),
        ),
        migrations.AlterField(
            model_name='datosmedicos',
            name='socio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='abmsocios.Socio'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='barrio',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='departamento',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='piso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='domicilios',
            field=models.ManyToManyField(null=True, to='abmsocios.Domicilio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_apto',
            field=models.DateField(null=True, verbose_name='fecha de apto fisico'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefonos',
            field=models.ManyToManyField(null=True, to='abmsocios.Telefono'),
        ),
    ]
