# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0004_auto_20170527_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='numero de telefono'),
        ),
    ]
