# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0005_auto_20170620_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Medicos',
            fields=[
                ('id_medico', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('osNumero_socio', models.BigIntegerField(null=True, verbose_name='numero de socio obra social')),
                ('os_plan', models.CharField(max_length=20, null=True, verbose_name='plan obra social')),
                ('contacto_urgencia', models.CharField(max_length=70, null=True, verbose_name='contacto de urgencia')),
                ('contacto_parentesco', models.CharField(max_length=20, null=True, verbose_name='parentesco')),
                ('numero_urgencia', models.IntegerField(null=True, verbose_name='numero en caso de urgencia')),
                ('obra_social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abmsocios.ObraSocial')),
            ],
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotoPerfil/', verbose_name='foto de perfil'),
        ),
        migrations.AlterModelTable(
            name='datosmedicos',
            table=None,
        ),
        migrations.AddField(
            model_name='datos_medicos',
            name='socio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='abmsocios.Socio'),
        ),
    ]
