# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0006_auto_20170628_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosmedicos',
            name='obra_social',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='socio',
        ),
        migrations.DeleteModel(
            name='DatosMedicos',
        ),
    ]
