# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0007_auto_20170628_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='domicilios',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='telefonos',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abmsocios.Socio'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abmsocios.Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_apto',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de apto fisico'),
        ),
    ]
