# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0008_auto_20170628_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='barrio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='departamento',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
