# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0009_auto_20170628_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_medicos',
            name='socio',
            field=models.OneToOneField(default='34982458', on_delete=django.db.models.deletion.CASCADE, to='abmsocios.Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
