# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 19:12
from __future__ import unicode_literals

import abmsocios.models.socio
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0010_auto_20170705_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='numero_socio',
            field=models.IntegerField(default=abmsocios.models.socio.Socio.generar_numero_socio, editable=False, unique=True, verbose_name='numero de socio'),
        ),
        migrations.AlterModelTable(
            name='datos_medicos',
            table='abmsocios_datos_medicos',
        ),
    ]
