# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abmsocios', '0011_auto_20170706_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotoPerfil/', verbose_name='foto usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='datos_medicos',
            name='contacto_parentesco',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='parentesco'),
        ),
        migrations.AlterField(
            model_name='datos_medicos',
            name='contacto_urgencia',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='contacto de urgencia'),
        ),
        migrations.AlterField(
            model_name='datos_medicos',
            name='id_medico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datos_medicos',
            name='numero_urgencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='numero en caso de urgencia'),
        ),
        migrations.AlterField(
            model_name='datos_medicos',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abmsocios.ObraSocial'),
        ),
        migrations.AlterField(
            model_name='datos_medicos',
            name='osNumero_socio',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='numero de socio obra social'),
        ),
        migrations.AlterField(
            model_name='datos_medicos',
            name='os_plan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='plan obra social'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='id_domicilio',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='id_telefono',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
