# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abmsocios', '0012_auto_20170712_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
